name: CI

on:
    push:
        branches:
            - '**' # Listen to all branches

jobs:
    test:
        runs-on: ubuntu-latest
        continue-on-error: ${{ github.ref != 'refs/heads/main' }} # Suppress failure notifications on non-main branches

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    notify:
        needs: test
        if: failure() && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
            - name: Send failure notification
              run: exit 1
